### ISSUE TITLE
Add language fr.js

### ISSUE THREAD

**Issue by hcornet** [wise2c-devops/deploy-ui#1]
const Index = {
  title: 'Bienvenue à utiliser le système de déploiement de composants kubernetes',
  button: 'démarrer',
  developers: 'Développeur',
  contact: 'Contactez nous'
}
const clusters = {
  add: {
    modalTile: 'Ajouter clusters',
    clusterName: 'Nom du cluster',
    clusterNameTips: 'Veuillez entrer le nom du cluster',
    clusterDescrtipion: 'Description'
  },
  menu: {
    host: 'Hôte',
    serviceComponents: 'Composants de service',
    installLog: 'Install logs'
  },
  delteTips: 'Êtes-vous sûr de vouloir supprimer le cluster??',
  routerName: 'Cluster'
}
const host = {
  addHostButton: 'Ajout hôte',
  delteTips: 'Êtes-vous sûr de vouloir supprimer l'hôte ?',
  table: {
    num: 'Nomber',
    name: 'Nom hôte',
    ip: 'IP',
    des: 'Description',
    operate: 'Opération'
  },
  hostModal: {
    modalTile: 'Hôte',
    hostName: 'nom d'hôte',
    hostNameTips: 'S'il vous plaît entrer le nom de l'hôte',
    hostIp: 'adresse ip hôte',
    hostIpTips: 'S'il vous plaît entrer une adresse IP validenter le nom de l'hôte',
    hostDescrtipion: 'Description'
  }
}

const componets = {
  startInstallButton: 'Démarrer installation',
  resets: 'Reset',
  addComponentsButton: 'Ajouter composant',
  delteTips: 'Êtes-vous sûr de vouloir supprimer le service ?',
  startInstallCulsterTips: 'Confirmez le début de l'installation du cluster',
  resetTips: 'Confirmer que le cluster est réinitialisé à l'état initial ?',
  resetSuccessMsg: 'Réinitialisation réussie. Le système a besoin de temps pour traiter la demande. Veuillez actualiser la page plus tard',
  table: {
    num: 'Nombre',
    serviceName: 'Nom de service',
    version: 'Version',
    attribute: 'Attribute',
    host: 'Hôte',
    operate: 'Operation'
  },
  componentModal: {
    modalTile: 'Service composant',
    componentType: 'Type de composant',
    version: 'Version',
    hostTips: 'Sélectionnez au moins un hôte',
    tips: 'S'il vous plaît, saisir une entrer valide'
  }
}

module.exports ={
  slectEmpty: 'vide',
  layer: {
    toggle: 'Validation du changement de langage',
    tips: 'Attention',
    deleteSuccess: 'Supprimer terminé',
    createSuccess: 'Création terminé',
    editSuccess: 'Mise à jour terminé',
    warnTips: 'S'il vous plaît remplir les paramètres requis et le soumettre'
  },
  tipsButton: {
    ok: 'Ok',
    cancel: 'Annuler',
    next: 'Suivant',
    prev: 'Précédent',
    back: 'Retour',
    done: 'Terminé'
  },
  Index: Index,
  clusters: clusters,
  host: host,
  componets: componets
}

**Comment by alanpeng** [comment]
Thank you very much. We will add this in our next release.

**Comment by alanpeng** [comment]
I just noticed that you wrote a grate article here: https://www.tips-of-mine.fr/?p=1170#chapitre5
Thanks for using Breeze. I have two things to tell you:
(1) Helm is integrated with Harbor in Breeze v1.14.1. You can execute helm command on any master nodes such as "helm repo list". (Harbor chartmuseum service works as a repo server for helm)
(2) Sometimes you would encounter the error during the Prometheus deployment, just go to the worker nodes you selected for Prometheus deployment and execute commands as below, I believe the problem would be fixed:
**cd /var/tmp/wise2c/prometheus**  
**remove.sh**

#watch the namespace "monitoring" until it disappears. then execute commands below#

**deploy.sh**
**add-on.sh**

**Comment by alanpeng** [comment]
https://raw.githubusercontent.com/wise2c-devops/deploy-ui/master/screenshot/Breeze-I18N-001.png
https://raw.githubusercontent.com/wise2c-devops/deploy-ui/master/screenshot/Breeze-I18N-002.png
https://raw.githubusercontent.com/wise2c-devops/deploy-ui/master/screenshot/Breeze-I18N-003.png
